### ISSUE TITLE
can't find class in Ubuntu14.04(jdk8)

### ISSUE THREAD

**Issue by kite-nubia** [tcalmant/jpype-py3#22]
``` python
from jpype import *
vmPath = getDefaultJVMPath()
jarPath = '/home/ringear/IdeaProjects/test/src/jpype/'

startJVM(vmPath, "-ea", "-Djava.class.path=%s" % (jarPath + 'Test.jar'))
tt = JClass('jpype.Test')
t = tt()
t.speak('ok')
shutdownJVM()
```

=========================Test.java===================

``` java
package jpype;

/**
 * Created by ringear on 16-8-18.
 */

public class Test {
    private String msg;

    public Test() {
        msg = "nothing so far...";
    }

    public static void speak(String msg) {
        System.out.println(msg);
    }

    public void setString(String s) {
        msg = s;
    }

    public String getString() {
        return msg;
    }
}
```
# 

in path "/home/ringear/IdeaProjects/test/src/jpype/"
step1.  javac Test.java (get Test.class)
step2.  jar -cvf Test.jar Test.class  (get Test.jar)

then python tt.py .get error code:

```
Traceback (most recent call last):
  File "tt.py", line 9, in <module>
    tt = JClass('jpype.Test')
  File "/home/ringear/anaconda3/lib/python3.4/site-packages/JPype1_py3-0.5.5.2-py3.4-linux-x86_64.egg/jpype/_jclass.py", line 57, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.ExceptionPyRaisable: java.lang.Exception: Class jpype.Test not found
```

**Comment by tcalmant** [comment]
The JAR isn't in the right format: it must contain a valid package structure.
``Test.class`` is at the root of the JAR file, while it should be in the ``jpype`` folder Inside the JAR file.

**Comment by tcalmant** [comment]
This project is now deprecated. Please use [jpype-project/jpype](https://github.com/jpype-project/jpype) instead.
